  # 日志配置
logging:
  level:
    org.springframework: info
    com.springboot: debug
    com.xaeport: debug
  config: classpath:config/logback-spring.xml


appConfig:
  systemName: 跨境通关辅助系统
#  domain: localhost
  entryDocu: false

#  uploadPath: D:\upload\
#    httpClinetUrl: http://localhost:8088
  #  httpClinetUrl: http://10.100.140.153:8088/

  modelFolder:
   Order: "model/跨境电子商务进口订单模板.xlsx"
   Waybill: "model/跨境电子商务运单模板.xlsx"
   WaybillStatus: "model/跨境电子商务运单状态模板.xlsx"
   Detail: "model/跨境电子商务进口清单模板.xlsx"
   Payment: "model/跨境电子商务进口支付单模板.xlsx"
  agentExeFolder: "model/xaeport_agent.exe"

  #录入单位名称
  inputCompanyName: "陕西中海经贸服务部"
  #录入单位代码
  inputCompanyCo: "6101999063"
  #录入人
  inputno: "9200000003043"
  senderId: "DXPENT0000015276"
  receiverId: "DXPEDC0000000001"
  xmlPath:
    sendPath: "kj/send"
    sendBakPath: "kj/sendBak"

  #下载文件夹
  downloadFolder: d:/app/download
  #回执文件夹
  receiptFolder: d:/app/receive
  #回执备份文件
  backupFolder: d:/app/backup
   # 错误目录，可以使用相对路径和绝对路径
  errorFolder: d:/app/error

# 数据源配置
spring:

    datasource:
        name: testSQL
        url: jdbc:oracle:thin:@10.100.140.160:1521:orcl
        username: kj
        password: "123456"
        type: com.alibaba.druid.pool.DruidDataSource
        platform: oracle
        driverClassName: oracle.jdbc.driver.OracleDriver
        initialSize: 1
        minIdle: 1
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        dbType: oracle
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 0
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    thymeleaf:
        cache: false

    main:
      # 禁用Banner
      banner-mode: 0
mybatis:
  configuration:
    callSettersOnNulls: true

management:
  port: 5210
  security:
    enabled: false

server:
  port: 8000
  session:
      timeout: 7200
      cookie:
        name: HACK
#        domain: localhost
#        domain: test.alacky
        http-only: true
  ssl:
    enabled: false
    key-store: cert/kstore2
    key-password: alacky
    key-store-password: alacky
    key-alias: jetty
    trust-store: cert/kstore2
  compression:
    enabled: true
#security:
#  basic:
#    enabled: false
#  ignored: /**



#  management:
#    address: 127.0.0.1
